/*globals define, WebGMEGlobal*/
/*jshint browser: true*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Wed Oct 18 2017 20:21:57 GMT-0500 (Central Daylight Time).
 */

define(['css!./styles/MOCAGrafanaVisualizerWidget.css'], function () {
    'use strict';

    var MOCAGrafanaVisualizerWidget,
        WIDGET_CLASS = 'm-o-c-a-grafana-visualizer';

    MOCAGrafanaVisualizerWidget = function (logger, container) {
        this._logger = logger.fork('Widget');

        this._el = container;

        this.nodes = {};
        this._initialize();

        this._logger.debug('ctor finished');

        this.grafanaIframe = null;
    };

    MOCAGrafanaVisualizerWidget.prototype._initialize = function (nodeData) {
        var width = this._el.width(),
            height = this._el.height(),
            self = this;

        if (!nodeData) {
            console.log('nodeData is empty. Something is wrong!');
            return;
        }

        // set widget class
        this._el.addClass(WIDGET_CLASS);

        // Create a dummy header 
        // this._el.append('<h3>MOCAGrafanaVisualizer Events:</h3>');

        var grafanaIframe = document.createElement('iframe');
        grafanaIframe.name = "grafana";
        grafanaIframe.style.height = "100%";
        grafanaIframe.style.width = "100%";

        grafanaIframe.src = this.getGrafanaUrl(nodeData);

        this._el.append(notebookIframe);

        this.notebookIframe = notebookIframe;

        // Registering to events can be done with jQuery (as normal)
        this._el.on('dblclick', function (event) {
            event.stopPropagation();
            event.preventDefault();
            self.onBackgroundDblClick();
        });
    };

    MOCAGrafanaVisualizerWidget.prototype.getGrafanaUrl = function (desc) {
        // Replace "localhost:9999" with "moca.isis.vanderbilt.edu" if you're running this on localhost
        return "http://moca.isis.vanderbilt.edu/grafana/";
    };

    MOCAGrafanaVisualizerWidget.prototype.onWidgetContainerResize = function (width, height) {
        this._logger.debug('Widget is resizing...');
    };

    // Adding/Removing/Updating items
    MOCAGrafanaVisualizerWidget.prototype.addNode = function (desc) {
        if (desc) {
            // Add node to a table of nodes
            var node = document.createElement('div'),
                label = 'children';

            if (desc.childrenIds.length === 1) {
                label = 'child';
            }

            this.nodes[desc.id] = desc;
            node.innerHTML = 'Adding node "' + desc.name + '" (click to view). It has ' + 
                desc.childrenIds.length + ' ' + label + '.';

            this._el.append(node);
            node.onclick = this.onNodeClick.bind(this, desc.id);
        }
    };

    MOCAGrafanaVisualizerWidget.prototype.removeNode = function (gmeId) {
        var desc = this.nodes[gmeId];
        this._el.append('<div>Removing node "' + desc.name + '"</div>');
        delete this.nodes[gmeId];
    };

    MOCAGrafanaVisualizerWidget.prototype.updateNode = function (desc) {
        if (desc) {
            this._logger.debug('Updating node:', desc);
            this._el.append('<div>Updating node "' + desc.name + '"</div>');
        }
    };

    /* * * * * * * * Visualizer event handlers * * * * * * * */

    MOCAGrafanaVisualizerWidget.prototype.onNodeClick = function (/*id*/) {
        // This currently changes the active node to the given id and
        // this is overridden in the controller.
    };

    MOCAGrafanaVisualizerWidget.prototype.onBackgroundDblClick = function () {
        this._el.append('<div>Background was double-clicked!!</div>');
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    MOCAGrafanaVisualizerWidget.prototype.destroy = function () {
    };

    MOCAGrafanaVisualizerWidget.prototype.onActivate = function () {
        this._logger.debug('MOCAGrafanaVisualizerWidget has been activated');
    };

    MOCAGrafanaVisualizerWidget.prototype.onDeactivate = function () {
        this._logger.debug('MOCAGrafanaVisualizerWidget has been deactivated');
    };

    return MOCAGrafanaVisualizerWidget;
});
