/*globals define, WebGMEGlobal*/
/*jshint browser: true*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Tue Oct 18 2016 15:26:27 GMT-0500 (Central Daylight Time).
 */

define(['css!./styles/MOCANotebookVisualizerWidget.css'], function () {
    'use strict';

    var MOCANotebookVisualizerWidget,
        WIDGET_CLASS = 'm-o-c-a-notebook-visualizer';

    MOCANotebookVisualizerWidget = function (logger, container) {
        this._logger = logger.fork('Widget');

        this._el = container;

        this.nodes = {};
        this._initialize();

        this._logger.debug('ctor finished');

        this.notebookIframe = null;
    };

    MOCANotebookVisualizerWidget.prototype._initialize = function (nodeData) {
        var width = this._el.width(),
            height = this._el.height(),
            self = this;

        if (!nodeData) {
            console.log('nodeData is empty. Something is wrong!');
            return;
        }

        // set widget class
        this._el.addClass(WIDGET_CLASS);

        // Create a dummy header 
        //this._el.append('<h3>MOCANotebookVisualizer Events:</h3>');
        var notebookIframe = document.createElement('iframe');
        notebookIframe.name = "notebook";
        notebookIframe.style.height = "100%";
        notebookIframe.style.width = "100%";
        //notebookIframe.src = "ipython";
        notebookIframe.src = this.getNotebookUrl(nodeData);
        this._el.append(notebookIframe);

        this.notebookIframe = notebookIframe;

        // Registering to events can be done with jQuery (as normal)
        this._el.on('dblclick', function (event) {
            event.stopPropagation();
            event.preventDefault();
            self.onBackgroundDblClick();
        });
    };

    MOCANotebookVisualizerWidget.prototype.onWidgetContainerResize = function (width, height) {
        this._logger.debug('Widget is resizing...');
    };

    MOCANotebookVisualizerWidget.prototype.getNotebookUrl = function (desc) {
        // Replace "localhost:9999" with "moca.isis.vanderbilt.edu" if you're running this on localhost
        if (desc.metaTypeName === 'Problem') {
            return "http://moca.isis.vanderbilt.edu/ipython/notebooks/" + WebGMEGlobal.userInfo._id + "/"
                + desc.projectName + "/"
                + desc.name + ".ipynb";
        } else if (desc.metaTypeName === 'DataDrivenComponent') {
            return "http://moca.isis.vanderbilt.edu/ipython/notebooks/" + WebGMEGlobal.userInfo._id + "/"
                + desc.projectName + "/lib/moca_ddmodels/"
                + desc.name + "/" + desc.name + ".ipynb";
        } else if (desc.metaTypeName === 'ProcessFlow') {
            return "http://moca.isis.vanderbilt.edu/ipython/notebooks/" + WebGMEGlobal.userInfo._id + "/"
                + desc.projectName + "/lib/moca_desmodels/"
                + desc.name + "/" + desc.name + ".ipynb";
        }
    };

    // Adding/Removing/Updating items
    MOCANotebookVisualizerWidget.prototype.addNode = function (desc) {
        if (desc) {
            // Add node to a table of nodes
            var node = document.createElement('div'),
                label = 'children';

            if (desc.childrenIds.length === 1) {
                label = 'child';
            }

            this.nodes[desc.id] = desc;
            node.innerHTML = 'Adding node "' + desc.name + '" (click to view). It has ' +
                desc.childrenIds.length + ' ' + label + '.';

            this._el.append(node);
            node.onclick = this.onNodeClick.bind(this, desc.id);
        }
    };

    MOCANotebookVisualizerWidget.prototype.removeNode = function (gmeId) {
        var desc = this.nodes[gmeId];
        this._el.append('<div>Removing node "' + desc.name + '"</div>');
        delete this.nodes[gmeId];
    };

    MOCANotebookVisualizerWidget.prototype.updateNode = function (desc) {
        if (desc) {
            this._logger.debug('Updating node:', desc);
            this._el.append('<div>Updating node "' + desc.name + '"</div>');
        }
    };

    /* * * * * * * * Visualizer event handlers * * * * * * * */

    MOCANotebookVisualizerWidget.prototype.onNodeClick = function (/*id*/) {
        // This currently changes the active node to the given id and
        // this is overridden in the controller.
    };

    MOCANotebookVisualizerWidget.prototype.onBackgroundDblClick = function () {
        this._el.append('<div>Background was double-clicked!!</div>');
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    MOCANotebookVisualizerWidget.prototype.destroy = function () {
        // TODO: Remove iframe here
    };

    MOCANotebookVisualizerWidget.prototype.onActivate = function () {
        this._logger.debug('MOCANotebookVisualizerWidget has been activated');
    };

    MOCANotebookVisualizerWidget.prototype.onDeactivate = function () {
        this._logger.debug('MOCANotebookVisualizerWidget has been deactivated');
    };

    return MOCANotebookVisualizerWidget;
});
